### ISSUE TITLE
Clear all

### ISSUE THREAD

**Issue by Gregcop1** [js-data/js-data-localforage#10]
Hi. Is there's a way to make localforage compatible with the `DS.clear`method to clear all stored datas in one shot instead of applying `destroyAll` resource by resource ?

**Comment by jmdobry** [comment]
There is not, but you can do:

``` js
await Promise.all(Object.keys(store.definitions).map((name) => store.destroyAll(name)))
// database is now empty
```

**Comment by Gregcop1** [comment]
Nice. Thanks a lot.

**Comment by jmdobry** [comment]
Closing because I’m not sure this is a bug. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-localforage, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

**Otherwise support is handled via [Stack Overflow](http://stackoverflow.com/questions/tagged/jsdata), [Slack chat](https://slack.js-data.io) or the [Mailing List](https://groups.io/org/groupsio/jsdata).**
